### ISSUE TITLE
support sub-directory pattern

### ISSUE THREAD

**Issue by giautm** [ReyahSolutions/matrix-git-generator#1]
Hi, I try to use your Actions with the filter:

```yml
      - name: Generate matrix
        id: generate_matrix
        uses: ReyahSolutions/matrix-git-generator@v1
        with:
          filters: |
            apps/*/**
```

But, the output currently has only the element `apps`. How I can get `apps/foo`, `apps/bar` (or `foo` / `bar`) from the changes? I think the below code is related.

https://github.com/ReyahSolutions/matrix-git-generator/blob/81c27a8f8fcace14d2669780cc0057bee33bf8db/src/main.ts#L18

**Comment by ArthurKnoep** [comment]
Hi,

Indeed it's currently not supported but we are open to contribution :smile:

I think the best strategy here would be to add a depth param to the filters, maybe we could achieve that with something like this:
```yaml
- name: Generate matrix
  id: generate_matrix
  uses: ReyahSolutions/matrix-git-generator@v1
  with:
    filters: |
      apps/*/**:2
```

**Comment by giautm** [comment]
Another way is support `baseDir`:
```yml
      - name: Generate matrix
        id: generate_matrix
        uses: ReyahSolutions/matrix-git-generator@v1
        with:
          baseDir: apps
          filters: |
            */**
 ```
